### ISSUE TITLE
Plug-ins being assigned to wrong instance of popcorn

### ISSUE THREAD

**Issue by cadecairos** [rwaldron/popcorn.sequence#13]
In some cases the plug-ins are being assigned to the wrong instance of popcorn in the pass-through function.  I have already fixed it and will create a pull request for review.

**Comment by rwaldron** [comment]
Nice, I'll keep an eye out for the fix

**Comment by cadecairos** [comment]
the fix was on line 516:
this.playlist[ idx ][ plugin ]( 

which changed to:
this.playlist[ play ][ plugin ]( 

I had this line changed in my last pull request (issue #11), accidentally.  I originally wanted to put it in two issues, but the tests for the plugins failed without this fix.

**Comment by rwaldron** [comment]
Thats ok, I'll forgive you... this time! :)
