### ISSUE TITLE
sequence.currentTime() missing

### ISSUE THREAD

**Issue by ghost** [rwaldron/popcorn.sequence#16]
Sequencer needs sequence.currentTime() functionality to get the currentTime of the sequence, not the video.

May be similar functionality to the "exec" function (with time offset of all previous clips)..
Could also be implemented in addition to seq.times.last (seq.times.timeOffset or so ), so it returns the seconds already played in previous clips of the same sequence.

See also here:
https://webmademovies.lighthouseapp.com/projects/63272/tickets/385

**Comment by tammo0** [comment]
fixed / close!

i wrote it for our project, alphawombat.
time for coffee :)
