### ISSUE TITLE
video end = sequence stop/end

### ISSUE THREAD

**Issue by tammo0** [rwaldron/popcorn.sequence#19]
When a Video in the Sequence shall be played to its very end the whole Sequence stops - no matter where it is.
Saying seq.play() the current video (which brokes the sequence) starts from its beginning.

**Comment by tammo0** [comment]
e.g.: Look at Obj2

SourcesObject:
[Object { src="./videos/5.webm", in=12, out=14}, Object { src="./videos/7.webm", in=17, **out=19.96**}, Object { src="./videos/7.webm", in=10, out=14}, Object { src="./videos/6.webm", in=0, out=2}]

###(Firefox 12, Win)###

seq.inOuts.ofClips:
{ in=0, out=2}, { in=3, **out=5.960000000000001**}, { in=6.960000000000001, out=10.96}, { in=11.96, out=12.96}

seq.inOuts.ofVideos:
{ in=12, out=14}, { in=17, **out=19.96**}, { in=10, out=14}, { in=1, out=2}

###(Chrome 18, Win)###
seq.inOuts.ofClips:
{in: 0, out: 2}, {in: 3, **out: 5.960000000000001**}, {in: 6.960000000000001, out: 10.96}, {in: 11.96, out: 12.96}

seq.inOuts.ofVideos:
{in: 12, out: 14}, {in: 17, **out: 19.96**}, {in: 10, out: 14}, {in: 1,out: 2}

**Comment by cadecairos** [comment]
resolved :)
