### ISSUE TITLE
seq.pause()

### ISSUE THREAD

**Issue by tammo0** [rwaldron/popcorn.sequence#26]
We need a function to pause the whole sequence.

**Comment by cadecairos** [comment]
can you open a pull request for that commit?

**Comment by tammo0** [comment]
see #27
did it but was not able to write a test in unit.js. it worked for me in a real website. i deleted my changed fork but will add it again for you.
Edit: ah, the code is still there. just a 1-liner

**Comment by cadecairos** [comment]
dupe on #31

**Comment by cadecairos** [comment]
**\* I mean #30
